int8 ZONE_Z1 = 1
int8 ZONE_Z2 = 2
int8 ZONE_Z3 = 3
int8 ZONE_Z4 = 4
int8 ZONE_Z5 = 5
int8 ZONE_Z6 = 6
int8 ZONE_Z7 = 7
int8 ZONE_Z8 = 8
int8 ZONE_Z9 = 9
int8 ZONE_Z10 = 10
int8 ZONE_Z11 = 11
int8 ZONE_Z12 = 12
int8 ZONE_Z13 = 13
int8 ZONE_Z14 = 14
int8 ZONE_Z15 = 15
int8 ZONE_Z16 = 16
int8 ZONE_Z17 = 17
int8 ZONE_Z18 = 18
int8 ZONE_Z19 = 19
int8 ZONE_Z20 = 20
int8 ZONE_Z21 = 21
int8 ZONE_Z22 = 22
int8 ZONE_Z23 = 23
int8 ZONE_Z24 = 24

int8 zone
int8 team
