# Machine name, type, and team
string    name
string    type
string    state
int8      team_color

uint32 input_tag
uint32 output_tag

geometry_msgs/Pose pose
# Which zone the machine is in, will be
# 0 during exploration phase (therefore not
# identify the actual zone)
int16      zone
uint32     rotation
bool       correctly_reported
uint32     loaded_with

# For RS also denote ring colors
int8[] rs_ring_colors
