
# Product complexity classes (determines number of required rings)
int8 C0 = 0
int8 C1 = 1
int8 C2 = 2
int8 C3 = 3

# ID and requested product of this order
uint32 id
int8   complexity
int8   base_color
int8[] ring_colors
int8   cap_color

# Quantity requested and delivered
uint32 quantity_requested
uint32 quantity_delivered_cyan
uint32 quantity_delivered_magenta

# Start and end time of the delivery
# period in seconds of game time
uint32 delivery_period_begin
uint32 delivery_period_end

# The gate to deliver to, defaults to any
# (non-defunct, i.e. non-red light) gate
uint32 delivery_gate
